# Generated by Django 6.0.3 on 2026-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
